-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Account CASCADE;
DROP TABLE IF EXISTS Vote CASCADE;
DROP TABLE IF EXISTS Conversation CASCADE;
DROP TABLE IF EXISTS Match CASCADE;
DROP TABLE IF EXISTS Message CASCADE;
DROP TABLE IF EXISTS Hashtag CASCADE;
